global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'apigateway'
    static_configs:
      - targets: ['host.docker.internal:7000']
  - job_name: 'getservice'
    static_configs:
      - targets: ['host.docker.internal:5160']
  - job_name: 'postservice'
    static_configs:
      - targets: ['postservice:5170']